ALL

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,43 +1,76 @@
-name: Chocolatine
+name: chocolatine
 
 on:
   push:
     branches:
-    - main
+      - '**'
+      - '!ga-ignore-*'
   pull_request:
     branches:
-    - main
+      - '**'
+      - '!ga-ignore-*'
+
+env:
+  MIRROR_URL: "git@github.com:UlysseZumbrunn/ChocolatineMiRRORTEST.git"
+  EXECUTABLES: ${{ secrets.EXECUTABLES }}
 
 jobs:
-  check_project:
+  check_coding_style:
     runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Install Dependencies
-      run: |
-        sudo apt-get update && sudo apt-get -y install build-essential
-    - name: Clean up unwanted files
-      run: |
-        UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
-        for FILE in $UNWANTED_FILES; do
-          echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
-        done
-        if [[ -n $UNWANTED_FILES ]]
-        then
-          exit 1
-        else
-          echo No unwanted files detected
-        fi
-    - name: Compile project
-      run: |
-        make
-        make clean
-    - name: Test project
-      run: |
-        make tests_run
-    - name: Push to mirror
-      uses: pixta-dev/repository-mirroring-action@v1
-      env:
-        TARGET_REPO_URL: ${{ secrets."git@github.com:UlysseZumbrunn/ChocolatineMiRRORTEST.git" }}
-        TARGET_REPO_BRANCH: ${{ github.ref }}
-        SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Run coding style checker
+        run: check.sh $(pwd) $(pwd)
+      - name: Display error annotations
+        if: failure()
+        uses: mathieudutour/github-actions-error-annotation@v3
+        with:
+          filename: 'output.log'
+      - name: Fail job on coding style errors
+        if: failure()
+        run: exit 1
+
+  check_program_compilation:
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker:latest
+    timeout-minutes: 2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Make
+        run: |
+          make
+          make clean
+      - name: Verify executables
+        run: |
+          for executable in $(echo "$EXECUTABLES" | sed "s/,/ /g"); do
+            if [ ! -x "$executable" ]; then
+              echo "Executable $executable not found or not executable"
+              exit 1
+            fi
+          done
+
+  run_tests:
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    timeout-minutes: 2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Make tests
+        run: make tests_run
+
+  push_to_mirror:
+    runs-on: ubuntu-latest
+    needs: [check_program_compilation, run_tests]
+    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Mirror repository
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          mirror_url: ${{ env.MIRROR_URL }}
+          private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
